---
- name: Install k3s (single node)
  become: true
  ansible.builtin.shell: |
    set -e
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s service to create kubeconfig
  become: true
  ansible.builtin.wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    timeout: 120

- name: Wait for Kubernetes API to be ready
  become: true
  ansible.builtin.shell: kubectl get nodes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: k8s_ready
  retries: 10
  delay: 6
  until: k8s_ready.rc == 0

- name: Create kube config directory for user
  become: true
  ansible.builtin.file:
    path: "{{ udemx_home }}/.kube"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: Copy admin kubeconfig to user home
  become: true
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ udemx_home }}/.kube/config"
    remote_src: true
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"
